<?php

namespace Database\Seeders\Backend\Setting;

use App\Models\Backend\Setting\ExamGroup;
use Illuminate\Database\Seeder;

class ExamGroupSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $exam_groups = [
            ['name' => 'Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '1'],
            ['name' => 'Humanities', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '1'],
            ['name' => 'Business Studies', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '1'],
            ['name' => 'Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '7'],
            ['name' => 'Humanities', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '7'],
            ['name' => 'Business Studies', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '7'],
            ['name' => 'Agriculture Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Architecture and Interior Design Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Automobile Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Civil Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Chemical Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Electrical Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Data Telecommunication and Network Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Electrical and Electronics Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Process Control Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Mechanical Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Mechatronics Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Power Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Refregeration & Air Conditioning Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Telecommunication Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Electronics Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Library Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Survey', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'General Mechanics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Firm Machinery', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Textile Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Others', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '2', 'exam_title_id' => '9'],
            ['name' => 'Akaid', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Akaid', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Arabic', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Archaeology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Bangla', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Development Studies', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Drama & Music', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Drawing and Printing', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'English', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Ethics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Fikha', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Fine Arts', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Folklore', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Graphics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Hadith', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'History', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'History of Music', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Home Economics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Industrial Arts', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'International Relations', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Islamic History and Culture', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Islamic Studies', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Language/Linguistic', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Library Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Modern Arabic', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Music', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Pali', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Persian', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Philosophy', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Sanskrit', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Tafsir', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'Urdu', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'World Religion', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '13'],
            ['name' => 'B.A', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '14'],
            ['name' => 'Music', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '14'],
            ['name' => 'Accounting', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '15'],
            ['name' => 'Finance', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '15'],
            ['name' => 'Management', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '15'],
            ['name' => 'Marketing', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '15'],
            ['name' => 'B.Com', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '16'],
            ['name' => 'Education', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '17'],
            ['name' => 'Anthropology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'Economics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'Mass Comm. & Journalism', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'Peace & Conflict', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'Political Science/Govt. and Politics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'Population Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'Public Administration', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'Public Finance', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'Social Welfare/Social Work', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'Sociology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'Urban Development', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'Women Studies', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '18'],
            ['name' => 'B.S.S', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '19'],
            ['name' => 'Agr.Co-operative & Marketing', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agriculture Chemistry', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agriculture Co-operatives', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agriculture Economics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agriculture Engineering', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agriculture Extension', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agriculture Finance', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agriculture Marketing', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agriculture Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agriculture Soil Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agriculture Statistics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agriculture Water Management', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agro Forestry', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agronnomy', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agronomy & Aquaculture', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Agronomy & Aquaculture Extension', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Anatomology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Anatomy & Histology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Animal Breeding & Genetic', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Animal Husbandry', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Animal Nutrition', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Animal Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Bio-Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Corp Botany', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Dairy Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Doc.of Veterinary Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Farm Power & Machinery', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Farm Structure', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Fisheries', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Fisheries & Aquaculture', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Fisheries Biology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Fisheries Management', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Fisheries Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Food Tech. & Rural Industry', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Forestry', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Horticulture', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Livestock', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Microbiology & Hygenic', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Paratrology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Plant Pathology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Poultry Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Production Economics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Rural Sociology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Surgery & Obstate', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '3', 'exam_title_id' => '20'],
            ['name' => 'Akaid', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '4', 'exam_title_id' => '34'],
            ['name' => 'General', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '2'],
            ['name' => 'Mujabbid', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '2'],
            ['name' => 'Science', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '2'],
            ['name' => 'Hifzul Quran', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '2'],
            ['name' => 'Business Studies', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '2'],
            ['name' => 'Agro Based Food', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'General Electronics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Automotive', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Building Maintenance', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Wood Working', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Ceramic', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Civil Construction', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Computer & Information Technology', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Civil Drafting with CAD', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Mechanical Drafting with CAD', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Dress Making', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Dying', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Printing and Finishing', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Electrical Maintenance Works', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Farm Machinery', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Fish Culture and Breeding', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Food Processing and Preservation', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'General Mechanics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Livestock Rearing and Farming', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Machine Tools Operation', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Poultry Rearing and Farming', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Patient Care Technique', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'General Electrical Works', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Plumbing and Pipe Fitting', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Refrigeration and Air-conditioning', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Glass', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Fruit and Vegetable Cultivation', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Weaving', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Welding and Fabrication', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Architectural Drafting with AutoCAD', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Knitting', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Shrimp Culture and Breeding', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '3'],
            ['name' => 'Creative and professional', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '4'],
            ['name' => 'English Language and Literature', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '4'],
            ['name' => 'Humanities and Social Sciences', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '4'],
            ['name' => 'Languages', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '4'],
            ['name' => 'Mathematics', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '4'],
            ['name' => 'Sciences', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '4'],
            ['name' => 'Dress Making', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '5'],
            ['name' => 'Dying Printing and Finishing', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '5'],
            ['name' => 'Weaving', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '5'],
            ['name' => 'Knitting', 'remarks' => 'n/a', 'enabled' => 'yes', 'exam_level_id' => '1', 'exam_title_id' => '5'],
        ];

        foreach ($exam_groups as $exam_group):
            ExamGroup::create($exam_group);
        endforeach;
    }
}
