<?php

namespace Database\Seeders\Backend\Setting;

use App\Models\Backend\Setting\Institute;
use Illuminate\Database\Seeder;

class InstituteSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $institutes = array(
            array('name' => 'Bangabandhu Sheikh Mujib Medical University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Bangabandhu Sheikh Mujibur Rahman Agricultural University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Bangladesh Agricultural University,Mymensingh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Bangladesh Open University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Bangladesh University of Engineering & Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Bangladesh University of Professionals','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Chittagong University of Engineering & Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Chittagong Veterinary and Animal Sciences University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Comilla University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Dhaka University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Dhaka University of Engineering & Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Hajee Mohammad Danesh Science & Technology University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Islamic University, Kushtia ','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Jagannath University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Jahangirnagar University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Jatiya Kabi Kazi Nazrul Islam University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Jessore Science & Technology University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Khulna University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Khulna University of Engineering and Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Mawlana Bhashani Science & Technology University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'National University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Noakhali Science & Technology University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Pabna University of Science and Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Patuakhali Science And Technology University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Rajshahi University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Rajshahi University of Engineering & Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Rangpur University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Shahjalal University of Science & Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Sher-e-Bangla Agricultural University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Sylhet Agricultural University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'University of Chittagong','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Ahsanullah University of Science and Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'America Bangladesh University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'American International University Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'ASA University Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Asian University of Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Atish Dipankar University of Science & Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Bangladesh Islami University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Bangladesh University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Bangladesh University of Business & Technology (BUBT)','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'BGC Trust University Bangladesh, Chittagong','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'BRAC University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'City University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Daffodil International University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Darul Ihsan University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Dhaka International University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'East Delta University , Chittagong','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'East West University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Eastern University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Gono Bishwabidyalay','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Green University of Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'IBAIS University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Independent University, Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'International Islamic University, Chittagong','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'International University of Business Agriculture & Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Leading University, Sylhet','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Manarat International University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Metropolitan University, Sylhet','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'North South University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Northern University Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Premier University, Chittagong','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Presidency University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Prime University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Primeasia University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Queens University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Royal University of Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Shanto Mariam University of Creative Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Southeast University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Southern University of Bangladesh , Chittagong','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Stamford University, Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'State University Of Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Sylhet International University, Sylhet','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'The Millenium University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'The Peoples University of Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'The University of Asia Pacific','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'United International University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'University of Development Alternative','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'University of Information Technology & Sciences','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'University of Liberal Arts Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'University of Science & Technology, Chittagong','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'University of South Asia','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Uttara University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Victoria University of Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'World University of Bangladesh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Asian University for Women','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Islamic University of Technology','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'South Asian University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Dhaka Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Sir Salimullah Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Mymensingh Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Chittagong Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Rajshahi Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'MAG Osmani Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Sher-E-Bangla Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Rangpur Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Comilla Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Khulna Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Shaheed Ziaur Rahman Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Dinajpur Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Faridpur Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Shaheed Suhrawardy Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Pabna Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Noakhali Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Cox`s Bazar Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Jessore Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Shaheed Nazrul Islam Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Kushtia Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Satkhira Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Sheikh Sayera Khatun Medical College, Gopalganj','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Feni Medical College,Feni','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Gono Bishwabidyalay, Savar, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Ad-din Womens Medical College, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Anwer Khan Modern Medical College, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Bangladesh Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Jalalabad Rageb-Rabeya Medical College,Sylhet','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'BGC Trust Medical College, Chittagong','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Central Medical College, Comilla','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Chottagram Ma-O-Shishu Hospital Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Community Based Medical College (cbmc), Mymensingh','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Community Medical College, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Delta Medical College, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Dhaka National Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Durra Samad Rahman Red Crescent Women�s Medical College, Sylhet','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Eastern Medical College, Comilla','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Enam Medical College, Savar, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Sylhet Women`s Medical College, Sylhet','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Green Life Medical College,Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Holy Family Red Crescent Medical College, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Ibrahim Medical College, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Ibn Sina Medical College, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'International Medical College, Gazipur','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Islami Bank Medical College, Rajshahi','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Jahurul Islam Medical College, Kishoregonj','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Jalalabad Ragib-Rabeya Medical College Sylhet','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Khawja Yunus Ali Medical College, Sirajganj','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Kumudini Medical College, Tangail','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Labaid Medical College[6] Dhanmondi, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Maulana Bhasani Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Medical College for Women and Hospital, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Nightingale Medical College, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'North Bengal Medical College, Sirajganj','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'North East Medical College, Sylhet','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Northern International Medical College, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Northern Private Medical College, Rangpur','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Popular Medical College & Hospital, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Prime Medical College, Rangpur','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Rangpur Community Hospital Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Sahabuddin Medical College and Hospital','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Samaj Vittik Medical College, Mirzanagar, Savar','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Shahabuddin Medical College, Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Z. H. Sikder Women`s Medical College','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Southern Medical College, Chittagong','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Tairunnessa Memorial Medical College, Gazipur','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'TMSS Medical College,Bogra','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'University Of Science and Technology Chittagong. IAMS','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Uttara Adhunik Medical College,Dhaka','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Military Institute of Science and Technology (MIST)','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Others','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3'),
            array('name' => 'Sonargaon University','remarks' => 'n/a','enabled' => 'yes','exam_level_id' => '3')
        );

        foreach ($institutes as $institute):
            Institute::create($institute);
        endforeach;
    }
}
